#!/usr/bin/env bash
# PR gate: combines the PR's signals into one required check, keeps a score,
# and posts a sticky scorecard comment. Generated by harness.
#
# Env (all optional except HEAD_SHA):
#   HEAD_SHA PR_NUMBER REPO GH_TOKEN
#   GUARD_ENABLED GUARD_AGENT GUARD_REASON GUARD_BLOCKING GUARD_BLOCK_COUNT GUARD_WARN_COUNT
#   REVIEW_ENABLED REVIEW_STATUS REVIEW_BLOCKING REVIEW_NITS REVIEW_PREEXISTING REVIEW_PATTERNS
#   REVIEW_BLOCKS (true: blocking review findings fail the gate)
#   PR_LABELS (comma-separated) OVERRIDE_LABEL (gate-override)
#   PREVIOUS_SCORECARD (JSON, for testing; otherwise read from the PR)
# A human can override a failing gate by adding the override label; the
# override is recorded on the scorecard.
set -euo pipefail

: "${HEAD_SHA:?}"
OVERRIDE_LABEL=${OVERRIDE_LABEL:-gate-override}
SUMMARY=${GITHUB_STEP_SUMMARY:-/dev/null}
num() { case ${1:-} in '' | *[!0-9]*) echo 0 ;; *) echo "$1" ;; esac; }

marker='<!-- harness-scorecard'
comment_id=''
previous=${PREVIOUS_SCORECARD:-}
if [ -z "$previous" ] && [ -n "${PR_NUMBER:-}" ] && [ -n "${REPO:-}" ] && command -v gh >/dev/null 2>&1; then
  existing=$(gh api --paginate "repos/$REPO/issues/$PR_NUMBER/comments" \
    --jq ".[] | select(.body | contains(\"$marker\")) | {id, body}" 2>/dev/null | tail -n 1 || true)
  if [ -n "$existing" ]; then
    comment_id=$(jq -r .id <<<"$existing")
    previous=$(jq -r .body <<<"$existing" | sed -n 's/^<!-- harness-scorecard \(.*\) -->$/\1/p')
  fi
fi

# ---- Review signal (reused from the last run on this commit when skipped) ------
r_status=${REVIEW_STATUS:-}
r_block=$(num "${REVIEW_BLOCKING:-}") r_nits=$(num "${REVIEW_NITS:-}") r_pre=$(num "${REVIEW_PREEXISTING:-}")
r_patterns=${REVIEW_PATTERNS:-}
if [ -n "${REVIEW_ENABLED:-}" ] && { [ -z "$r_status" ] || [ "$r_status" = skipped ]; } && [ -n "$previous" ] &&
  [ "$(jq -r .head_sha <<<"$previous")" = "$HEAD_SHA" ]; then
  r_status=$(jq -r '.review.status' <<<"$previous")
  r_block=$(jq -r '.review.blocking' <<<"$previous")
  r_nits=$(jq -r '.review.nits' <<<"$previous")
  r_pre=$(jq -r '.review.preexisting' <<<"$previous")
  r_patterns=$(jq -r '.review.patterns' <<<"$previous")
fi
[ -n "${REVIEW_ENABLED:-}" ] || r_status=off
[ -n "$r_status" ] || r_status=skipped

g_block=$(num "${GUARD_BLOCK_COUNT:-}") g_warn=$(num "${GUARD_WARN_COUNT:-}")
agent=${GUARD_AGENT:-false}

# ---- Verdict --------------------------------------------------------------------
reasons=''
if [ "${REVIEW_BLOCKS:-true}" = true ] && [ "$r_block" -gt 0 ]; then
  reasons="$reasons- $r_block blocking AI review finding(s)\n"
fi
if [ "${GUARD_BLOCKING:-false}" = true ]; then
  reasons="$reasons- agent-guard blocking finding(s) on an agent-authored PR\n"
fi
override=false
case ",${PR_LABELS:-}," in *",$OVERRIDE_LABEL,"*) override=true ;; esac

if [ -z "$reasons" ]; then verdict=pass
elif [ "$override" = true ]; then verdict=overridden
else verdict=fail; fi

# Score: transparent heuristic, comparable across PRs (see the formula below).
score=$((100 - 20 * r_block - 3 * r_nits - 15 * g_block - 5 * g_warn))
[ "$score" -ge 0 ] || score=0

case $verdict in
  pass) head='✅ PR gate: pass' ;;
  overridden) head="⚠️ PR gate: overridden by \`$OVERRIDE_LABEL\`" ;;
  fail) head='❌ PR gate: fail' ;;
esac
case $r_status in
  ok) review_cell="$r_block 🔴 blocking · $r_nits 🟡 nits · $r_pre 🟣 pre-existing" ;;
  off) review_cell='not enabled' ;;
  error) review_cell='⚠️ errored (does not block; see the review job)' ;;
  *) review_cell='skipped (draft, fork, or no API key)' ;;
esac
if [ -n "${GUARD_ENABLED:-}" ]; then guard_cell="$g_block blocking-class · $g_warn warnings"; else guard_cell='not enabled'; fi

json=$(jq -cn --arg sha "$HEAD_SHA" --arg verdict "$verdict" --argjson score "$score" --arg agent "$agent" \
  --arg rs "$r_status" --argjson rb "$r_block" --argjson rn "$r_nits" --argjson rp "$r_pre" --arg pat "$r_patterns" \
  --argjson gb "$g_block" --argjson gw "$g_warn" --argjson ov "$override" \
  '{v: 1, head_sha: $sha, verdict: $verdict, score: $score, agent: ($agent == "true"),
    review: {status: $rs, blocking: $rb, nits: $rn, preexisting: $rp, patterns: $pat},
    guard: {block: $gb, warn: $gw}, override: $ov}')

body=$(
  echo "## $head"
  echo
  echo "| Signal | Result |"
  echo "|---|---|"
  if [ "$agent" = true ]; then echo "| Authored by | 🤖 agent (${GUARD_REASON:-detected}) |"; else echo "| Authored by | human |"; fi
  echo "| AI review | $review_cell |"
  echo "| Agent guard | $guard_cell |"
  echo "| Score | **$score**/100 |"
  if [ -n "$reasons" ]; then
    echo
    echo "**Why it fails:**"
    printf '%b' "$reasons"
    echo
    echo "Fix the findings and push. A maintainer may add the \`$OVERRIDE_LABEL\` label to accept the risk; the override is recorded here."
  fi
  echo
  echo "<sub>Score = 100 − 20×blocking − 3×nits − 15×guard blocking-class − 5×guard warnings. Commit ${HEAD_SHA:0:7}.</sub>"
  echo
  echo "$marker $json -->"
)

printf '%s\n' "$body" >>"$SUMMARY"
printf '%s\n' "$body" >"${SCORECARD_OUT:-/dev/null}"

if [ -n "${PR_NUMBER:-}" ] && [ -n "${REPO:-}" ] && command -v gh >/dev/null 2>&1 && [ -z "${NO_POST:-}" ]; then
  if [ -n "$comment_id" ]; then
    gh api --method PATCH "repos/$REPO/issues/comments/$comment_id" -f body="$body" >/dev/null || true
  else
    gh api --method POST "repos/$REPO/issues/$PR_NUMBER/comments" -f body="$body" >/dev/null || true
  fi
fi

[ "$verdict" != fail ]
