#!/usr/bin/env bash
# PR gate: combines the PR's signals into one required check, keeps a score,
# and posts a sticky scorecard comment. Generated by harness.
#
# Env (all optional except HEAD_SHA):
#   HEAD_SHA PR_NUMBER REPO GH_TOKEN PR_AUTHOR
#   GUARD_ENABLED GUARD_RESULT GUARD_AGENT GUARD_REASON GUARD_BLOCKING GUARD_BLOCK_COUNT GUARD_WARN_COUNT
#   REVIEW_ENABLED REVIEW_RESULT REVIEW_EXPECTED REVIEW_STATUS REVIEW_BLOCKING REVIEW_NITS
#   REVIEW_PREEXISTING REVIEW_FAILED REVIEW_PATTERNS
#   REVIEW_BLOCKS (true: blocking review findings fail the gate)
#   PR_LABELS (comma-separated) OVERRIDE_LABEL (gate-override)
#   For testing instead of the GitHub API: PREVIOUS_SCORECARD, OVERRIDE_ACTOR
#
# Only this workflow's bot comments are trusted as previous scorecards. A human
# other than the PR author can override a failing gate with the override
# label; the override and who applied it are recorded on the scorecard.
set -euo pipefail

: "${HEAD_SHA:?}"
OVERRIDE_LABEL=${OVERRIDE_LABEL:-gate-override}
SUMMARY=${GITHUB_STEP_SUMMARY:-/dev/null}
num() { case ${1:-} in '' | *[!0-9]*) echo 0 ;; *) echo "$1" ;; esac; }
api() { [ -n "${PR_NUMBER:-}" ] && [ -n "${REPO:-}" ] && command -v gh >/dev/null 2>&1; }

marker='<!-- harness-scorecard'
comment_id=''
previous=${PREVIOUS_SCORECARD:-}
if [ -z "$previous" ] && api; then
  existing=$(gh api --paginate "repos/$REPO/issues/$PR_NUMBER/comments" \
    --jq ".[] | select(.user.type == \"Bot\" and (.body | contains(\"$marker\"))) | {id, body}" 2>/dev/null | tail -n 1 || true)
  if [ -n "$existing" ]; then
    comment_id=$(jq -r .id <<<"$existing" 2>/dev/null || true)
    previous=$(jq -r .body <<<"$existing" 2>/dev/null | sed -n 's/^<!-- harness-scorecard \(.*\) -->$/\1/p' || true)
  fi
fi
jq -e 'type == "object"' >/dev/null 2>&1 <<<"$previous" || previous=''
prev() { jq -r "$1 // empty" <<<"$previous" 2>/dev/null || true; }

# ---- Review signal --------------------------------------------------------------
r_status=${REVIEW_STATUS:-} r_block=$(num "${REVIEW_BLOCKING:-}") r_nits=$(num "${REVIEW_NITS:-}")
r_pre=$(num "${REVIEW_PREEXISTING:-}") r_failed=$(num "${REVIEW_FAILED:-}") r_patterns=${REVIEW_PATTERNS:-}
pending=''
if [ -z "${REVIEW_ENABLED:-}" ]; then
  r_status=off
elif [ "${REVIEW_RESULT:-}" = failure ] || [ "${REVIEW_RESULT:-}" = cancelled ]; then
  r_status=error
elif [ -z "$r_status" ]; then
  # The review job didn't run for this event (e.g. a label change). Reuse the
  # last review of this exact commit; if there is none, the gate waits.
  if [ -n "$previous" ] && [ "$(prev .head_sha)" = "$HEAD_SHA" ]; then
    r_status=$(prev .review.status)
    r_block=$(num "$(prev .review.blocking)") r_nits=$(num "$(prev .review.nits)")
    r_pre=$(num "$(prev .review.preexisting)") r_failed=$(num "$(prev .review.failed)")
    r_patterns=$(prev .review.patterns)
  elif [ "${REVIEW_EXPECTED:-false}" = true ]; then
    r_status=pending pending=1
  else
    r_status=skipped
  fi
fi
case $r_status in ok | partial | error | skipped | off | pending) ;; *) r_status=error ;; esac
r_patterns=$(printf '%s' "$r_patterns" | tr -cd 'a-z0-9,-')

# ---- Guard signal -----------------------------------------------------------------
g_block=$(num "${GUARD_BLOCK_COUNT:-}") g_warn=$(num "${GUARD_WARN_COUNT:-}")
agent=${GUARD_AGENT:-false}
[ "$agent" = true ] || agent=false
g_error=''
if [ -n "${GUARD_ENABLED:-}" ] && { [ "${GUARD_RESULT:-}" = failure ] || [ "${GUARD_RESULT:-}" = cancelled ]; }; then
  g_error=1
fi

# ---- Verdict --------------------------------------------------------------------
reasons=''
if [ "${REVIEW_BLOCKS:-true}" = true ] && [ "$r_block" -gt 0 ]; then
  reasons="$reasons- $r_block blocking AI review finding(s)\n"
fi
if [ "${GUARD_BLOCKING:-false}" = true ]; then
  reasons="$reasons- agent-guard blocking finding(s) on an agent-authored PR\n"
fi
if [ -n "$g_error" ]; then
  reasons="$reasons- the agent guard job did not complete; re-run the workflow\n"
fi
if [ -n "$pending" ]; then
  reasons="$reasons- the AI review has not completed for this commit yet (it runs on push; re-run this workflow once it has finished)\n"
fi

# Override: the label must be present and added by someone other than the PR
# author and other than a bot.
override=false override_note='' actor=''
case ",${PR_LABELS:-}," in
  *",$OVERRIDE_LABEL,"*)
    actor=${OVERRIDE_ACTOR:-}
    if [ -z "$actor" ] && api; then
      actor=$(gh api --paginate "repos/$REPO/issues/$PR_NUMBER/events" \
        --jq "[.[] | select(.event == \"labeled\" and .label.name == \"$OVERRIDE_LABEL\")] | last | .actor.login // empty" 2>/dev/null | tail -n 1 || true)
    fi
    actor=$(printf '%s' "$actor" | tr -cd 'A-Za-z0-9[]_.-')
    if [ -z "$actor" ]; then
      override_note="override label present but its author is unknown; ignored"
    elif [ "$actor" = "${PR_AUTHOR:-}" ]; then
      override_note="override label added by the PR author ($actor); ignored"
    else
      case $actor in
        *'[bot]') override_note="override label added by a bot ($actor); ignored" ;;
        *) override=true ;;
      esac
    fi
    ;;
esac

if [ -z "$reasons" ]; then verdict=pass
elif [ -n "$pending" ]; then verdict=pending
elif [ "$override" = true ]; then verdict=overridden
else verdict=fail; fi

# Score: transparent heuristic, comparable across PRs (see the formula below).
score=$((100 - 20 * r_block - 3 * r_nits - 15 * g_block - 5 * g_warn))
[ "$score" -ge 0 ] || score=0

case $verdict in
  pass) head='✅ PR gate: pass' ;;
  pending) head='⏳ PR gate: waiting for the AI review' ;;
  overridden) head="⚠️ PR gate: overridden by @$actor with \`$OVERRIDE_LABEL\`" ;;
  fail) head='❌ PR gate: fail' ;;
esac
case $r_status in
  ok) review_cell="$r_block 🔴 blocking · $r_nits 🟡 nits · $r_pre 🟣 pre-existing" ;;
  partial) review_cell="$r_block 🔴 blocking · $r_nits 🟡 nits · $r_pre 🟣 pre-existing (⚠️ $r_failed pass(es) failed: incomplete)" ;;
  off) review_cell='not enabled' ;;
  error) review_cell='⚠️ errored: not counted, does not block (see the review job)' ;;
  pending) review_cell='⏳ not yet run for this commit' ;;
  *) review_cell='skipped (draft, fork, or no API key)' ;;
esac
if [ -z "${GUARD_ENABLED:-}" ]; then guard_cell='not enabled'
elif [ -n "$g_error" ]; then guard_cell='⚠️ did not complete'
else guard_cell="$g_block blocking-class · $g_warn warnings"; fi

json=$(jq -cn --arg sha "$HEAD_SHA" --arg verdict "$verdict" --argjson score "$score" --argjson agent "$agent" \
  --arg rs "$r_status" --argjson rb "$r_block" --argjson rn "$r_nits" --argjson rp "$r_pre" --argjson rf "$r_failed" \
  --arg pat "$r_patterns" --argjson gb "$g_block" --argjson gw "$g_warn" --argjson ov "$override" --arg by "$actor" \
  '{v: 1, head_sha: $sha, verdict: $verdict, score: $score, agent: $agent,
    review: {status: $rs, blocking: $rb, nits: $rn, preexisting: $rp, failed: $rf, patterns: $pat},
    guard: {block: $gb, warn: $gw}, override: $ov, override_by: (if $ov then $by else null end)}')

body=$(
  echo "## $head"
  echo
  echo "| Signal | Result |"
  echo "|---|---|"
  if [ "$agent" = true ]; then
    echo "| Authored by | 🤖 agent ($(printf '%s' "${GUARD_REASON:-detected}" | tr -d '|<>' | cut -c1-80)) |"
  else
    echo "| Authored by | human |"
  fi
  echo "| AI review | $review_cell |"
  echo "| Agent guard | $guard_cell |"
  echo "| Score | **$score**/100 |"
  if [ -n "$reasons" ]; then
    echo
    if [ "$verdict" = pending ]; then echo "**Waiting on:**"; else echo "**Why it fails:**"; fi
    printf '%b' "$reasons"
    echo
    echo "Fix the findings and push. A maintainer other than the PR author may add the \`$OVERRIDE_LABEL\` label to accept the risk; the override is recorded here."
  fi
  [ -z "$override_note" ] || printf '\n_%s._\n' "$override_note"
  echo
  echo "<sub>Score = 100 − 20×blocking − 3×nits − 15×guard blocking-class − 5×guard warnings. Commit ${HEAD_SHA:0:7}.</sub>"
  echo
  echo "$marker $json -->"
)

printf '%s\n' "$body" >>"$SUMMARY"
printf '%s\n' "$body" >"${SCORECARD_OUT:-/dev/null}"

if api && [ -z "${NO_POST:-}" ]; then
  if [ -n "$comment_id" ]; then
    gh api --method PATCH "repos/$REPO/issues/comments/$comment_id" -f body="$body" >/dev/null || true
  else
    gh api --method POST "repos/$REPO/issues/$PR_NUMBER/comments" -f body="$body" >/dev/null || true
  fi
fi

[ "$verdict" = pass ] || [ "$verdict" = overridden ]
