version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
{{#if DEPENDABOT_ECOSYSTEM}}
  - package-ecosystem: {{DEPENDABOT_ECOSYSTEM}}
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types: [minor, patch]
{{/if}}
