#!/usr/bin/env bash
# AI code review for the PR gate. Generated by harness.
#
# Each pass is an independent, non-interactive Claude Code instance (`claude -p`)
# with read-only tools and a fresh context, never the session that wrote the
# code. One pass per changed file looks for local issues; then one cross-file
# pass looks at data flow and interfaces. Output is schema-validated JSON
# (--output-format json --json-schema). Findings get a stable fingerprint, so
# re-runs report only new issues and count still-unfixed ones without
# reposting them.
#
# Env: BASE_SHA HEAD_SHA, plus for posting: PR_NUMBER REPO GH_TOKEN.
# Optional: CLAUDE_BIN (claude), REVIEW_MODEL, MAX_FILES (20),
#           MIN_INLINE_CONFIDENCE (0.5), OUT_DIR (.harness-review),
#           PRIOR_FILE (JSON array of prior markers, for testing), NO_POST.
# Step outputs: status blocking nits preexisting posted patterns
set -euo pipefail

: "${BASE_SHA:?}" "${HEAD_SHA:?}"
CLAUDE_BIN=${CLAUDE_BIN:-claude}
MAX_FILES=${MAX_FILES:-20}
MIN_CONF=${MIN_INLINE_CONFIDENCE:-0.5}
OUT=${OUT_DIR:-.harness-review}
OUTPUT=${GITHUB_OUTPUT:-/dev/null}
RANGE="$BASE_SHA...$HEAD_SHA"
CRITERIA=.github/review/criteria.md
SCHEMA=.github/review/findings.schema.json
SKIP='(^|/)(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|bun\.lockb?|uv\.lock|poetry\.lock|go\.sum|Cargo\.lock|Gemfile\.lock)$|\.(png|jpe?g|gif|ico|pdf|zip|gz|ipynb|map)$|\.min\.js$|(^|/)(dist|build|vendor|node_modules)/'
mkdir -p "$OUT"

emit() { printf '%s=%s\n' "$1" "$2" >>"$OUTPUT"; }
finish() { # status blocking nits preexisting posted patterns
  emit status "$1"
  emit blocking "${2:-0}"
  emit nits "${3:-0}"
  emit preexisting "${4:-0}"
  emit posted "${5:-0}"
  emit patterns "${6:-}"
  exit 0
}
sha() { if command -v sha256sum >/dev/null 2>&1; then sha256sum; else shasum -a 256; fi | cut -c1-12; }

if ! command -v "$CLAUDE_BIN" >/dev/null 2>&1; then
  echo "ai-review: '$CLAUDE_BIN' not found; skipping" >&2
  finish skipped
fi
if [ -z "${ANTHROPIC_API_KEY:-}" ] && [ -z "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
  echo "ai-review: no ANTHROPIC_API_KEY secret configured; skipping" >&2
  finish skipped
fi

files=$(git diff --name-only --diff-filter=AMR "$RANGE" | grep -Ev "$SKIP" || true)
if [ -z "$files" ]; then finish ok; fi
nfiles=$(printf '%s\n' "$files" | wc -l | tr -d ' ')

# ---- Prior findings (from earlier runs' inline comments) ---------------------
prior=$OUT/prior.json
if [ -n "${PRIOR_FILE:-}" ]; then
  cp "$PRIOR_FILE" "$prior"
elif [ -n "${PR_NUMBER:-}" ] && [ -n "${REPO:-}" ] && command -v gh >/dev/null 2>&1; then
  gh api --paginate "repos/$REPO/pulls/$PR_NUMBER/comments" \
    --jq '.[] | .body | select(contains("<!-- harness-review:")) | capture("<!-- harness-review:(?<j>\\{.*\\}) -->").j | fromjson' \
    2>/dev/null | jq -s '.' >"$prior" || echo '[]' >"$prior"
else
  echo '[]' >"$prior"
fi

# ---- Passes -----------------------------------------------------------------
schema=$(cat "$SCHEMA")
claude_args=(-p --output-format json --json-schema "$schema" --allowedTools "Read,Grep,Glob" --max-turns 20)
if [ -n "${REVIEW_MODEL:-}" ]; then claude_args+=(--model "$REVIEW_MODEL"); fi

preamble() {
  cat <<EOF
You are an independent code reviewer running in CI on a pull request. You did not write this change; judge only the diff and the code. You may Read, Grep, and Glob the repository for context. Follow the review criteria below exactly, including categories that are switched off. Respond only through the required JSON schema.

## Review criteria

$(cat "$CRITERIA")

## Prior findings on this pull request

Do not report these again as new. If one is still unfixed, report it with status "still_present" and the same path, category, and detected_pattern.

$(jq -c '.[] | {path, category: .cat, detected_pattern: .pattern, severity: .sev, title}' "$prior")
EOF
}

run_pass() { # name prompt-file -> $OUT/pass-<name>.json (array of findings)
  local name=$1 raw=$OUT/raw-$1.json
  if ! "$CLAUDE_BIN" "${claude_args[@]}" <"$2" >"$raw" 2>"$OUT/err-$name.log"; then
    echo "ai-review: pass '$name' failed (see $OUT/err-$name.log)" >&2
    return 1
  fi
  if ! jq -e '(.structured_output // (.result | fromjson? // .)) | .findings | arrays' "$raw" >"$OUT/pass-$name.json" 2>/dev/null; then
    echo "ai-review: pass '$name' returned no structured findings" >&2
    return 1
  fi
  jq -r '(.structured_output // (.result | fromjson? // .)) | .summary // empty' "$raw" >>"$OUT/summaries.txt" 2>/dev/null || true
}

: >"$OUT/summaries.txt"
ok=0 failed=0 i=0 reviewed=()
while IFS= read -r f; do
  [ "$i" -lt "$MAX_FILES" ] || break
  i=$((i + 1))
  reviewed+=("$f")
  {
    preamble
    printf '\n## This pass\n\nLocal review of ONE file: `%s`. Report only issues located in this file. A separate pass handles cross-file issues.\n\n```diff\n' "$f"
    git diff -U15 "$RANGE" -- "$f" | head -c 60000
    printf '\n```\n'
  } >"$OUT/prompt-$i.txt"
  if run_pass "file$i" "$OUT/prompt-$i.txt"; then ok=$((ok + 1)); else failed=$((failed + 1)); fi
done <<EOF
$files
EOF

if [ "$nfiles" -gt 1 ]; then
  {
    preamble
    printf '\n## This pass\n\nCross-file integration review. Per-file passes already covered local issues (titles below; do not repeat them). Look only for problems that span files: data flow, interface and contract mismatches, inconsistent handling of the same case, missing updates to callers or tests.\n\nLocal findings so far:\n'
    cat "$OUT"/pass-file*.json 2>/dev/null | jq -r '.[] | "- \(.path): \(.title)"' || true
    printf '\n```diff\n'
    git diff -U5 "$RANGE" -- "${reviewed[@]}" | head -c 150000
    printf '\n```\n'
  } >"$OUT/prompt-cross.txt"
  if run_pass cross "$OUT/prompt-cross.txt"; then ok=$((ok + 1)); else failed=$((failed + 1)); fi
fi

if [ "$ok" -eq 0 ]; then finish error; fi

# ---- Merge, fingerprint, dedupe ------------------------------------------------
: >"$OUT/fp.jsonl"
while IFS= read -r finding; do
  fp=$(printf '%s|%s|%s' "$(jq -r .path <<<"$finding")" "$(jq -r .category <<<"$finding")" \
    "$(jq -r .detected_pattern <<<"$finding")" | sha)
  jq -c --arg fp "$fp" '. + {fp: $fp}' <<<"$finding" >>"$OUT/fp.jsonl"
done < <(cat "$OUT"/pass-*.json | jq -c '.[]')

jq -s --slurpfile prior "$prior" '
  def rank: {"blocking": 0, "nit": 1, "pre-existing": 2}[.severity];
  group_by(.fp) | map(sort_by(rank) | .[0])
  | ($prior[0] | map(.fp)) as $seen
  | map(. + {already_posted: (.fp as $f | $seen | index($f) != null)})
' "$OUT/fp.jsonl" >"$OUT/findings.json"

count() { jq --arg s "$1" '[.[] | select(.severity == $s)] | length' "$OUT/findings.json"; }
blocking=$(count blocking)
nits=$(count nit)
pre=$(count pre-existing)
patterns=$(jq -r '[.[].detected_pattern] | group_by(.) | map({p: .[0], n: length}) | sort_by(-.n) | .[0:3] | map(.p) | join(",")' "$OUT/findings.json")

# ---- Build the review: inline where the line is in the diff, else in the body --
valid_lines() { # file -> "start end" ranges of new-side lines visible in the diff
  git diff -U3 "$RANGE" -- "$1" | sed -n 's/^@@ -[0-9,]* +\([0-9]*\),\{0,1\}\([0-9]*\) @@.*/\1 \2/p' |
    awk '{ n = ($2 == "") ? 1 : $2; if (n > 0) print $1, $1 + n - 1 }'
}
: >"$OUT/inline.jsonl"
: >"$OUT/body.md"
while IFS= read -r finding; do
  path=$(jq -r .path <<<"$finding")
  line=$(jq -r '.line // empty' <<<"$finding")
  conf=$(jq -r .confidence <<<"$finding")
  inline=''
  if [ -n "$line" ] && awk -v c="$conf" -v m="$MIN_CONF" 'BEGIN { exit !(c >= m) }'; then
    while read -r lo hi; do
      if [ "$line" -ge "$lo" ] && [ "$line" -le "$hi" ]; then inline=1; fi
    done < <(valid_lines "$path")
  fi
  comment=$(jq -r '
    ({"blocking": "🔴 **Blocking**", "nit": "🟡 **Nit**", "pre-existing": "🟣 **Pre-existing**"}[.severity]) as $sev
    | "\($sev) · `\(.category)`: \(.title)\n\n\(.detail)"
      + (if .suggested_fix then "\n\n**Suggested fix:** \(.suggested_fix)" else "" end)
      + "\n\n<sub>pattern `\(.detected_pattern)` · confidence \(.confidence) · react 👎 if this is a false positive</sub>"
      + "\n<!-- harness-review:" + ({fp, path, cat: .category, pattern: .detected_pattern, sev: .severity, title: (.title | gsub("-->"; "—>"))} | tojson) + " -->"' <<<"$finding")
  if [ -n "$inline" ]; then
    jq -cn --arg path "$path" --argjson line "$line" --arg body "$comment" \
      '{path: $path, line: $line, side: "RIGHT", body: $body}' >>"$OUT/inline.jsonl"
  else
    printf -- '- `%s%s` %s\n' "$path" "${line:+:$line}" "$(jq -r '"\(.severity): \(.title) (confidence \(.confidence))"' <<<"$finding")" >>"$OUT/body.md"
  fi
done < <(jq -c '.[] | select(.already_posted | not)' "$OUT/findings.json")

posted=$(wc -l <"$OUT/inline.jsonl" | tr -d ' ')
still=$(jq '[.[] | select(.already_posted)] | length' "$OUT/findings.json")
{
  echo "### AI review"
  echo
  sed 's/^/> /' "$OUT/summaries.txt" | head -n 20
  echo
  echo "Findings: **$blocking** blocking · **$nits** nits · **$pre** pre-existing ($posted new inline, $still from earlier runs). Reviewed $i of $nfiles files$([ "$failed" -eq 0 ] || printf '; %s pass(es) failed' "$failed")."
  if [ -s "$OUT/body.md" ]; then
    echo
    echo "Not attached to a diff line, or low confidence (needs a human look):"
    cat "$OUT/body.md"
  fi
  echo
  echo "<sub>Independent Claude Code review per .github/review/criteria.md. React 👎 on false positives; the weekly digest tracks them by pattern.</sub>"
} >"$OUT/review-body.md"
cat "$OUT/review-body.md" >>"${GITHUB_STEP_SUMMARY:-/dev/null}"

jq -n --arg commit "$HEAD_SHA" --rawfile body "$OUT/review-body.md" --slurpfile comments "$OUT/inline.jsonl" \
  '{commit_id: $commit, event: "COMMENT", body: $body, comments: $comments}' >"$OUT/review-payload.json"

new_count=$(jq '[.[] | select(.already_posted | not)] | length' "$OUT/findings.json")
if [ -z "${NO_POST:-}" ] && [ "$new_count" -gt 0 ] && [ -n "${PR_NUMBER:-}" ] && [ -n "${REPO:-}" ]; then
  gh api --method POST "repos/$REPO/pulls/$PR_NUMBER/reviews" --input "$OUT/review-payload.json" >/dev/null ||
    echo "ai-review: posting the review failed; findings are in the job summary" >&2
fi

finish ok "$blocking" "$nits" "$pre" "$posted" "$patterns"
