# shellcheck shell=bash
# Persistent state inside the target repo:
#   .harness/config    answers from the wizard (KEY=value), committed to git
#   .harness/manifest  "<sha256>  <path>" for every whole-file managed by harness
# Together they make `harness update` reproducible and safe to re-run.

ANSWER_KEYS="PROJECT_NAME STACK PKG_MANAGER INSTALL_CMD LINT_CMD TYPECHECK_CMD TEST_CMD FORMAT_CMD DEFAULT_BRANCH CODEOWNERS AGENT_TOOLS GUARD_LEVEL MODULES OTEL_ENDPOINT DIFF_BUDGET"

config_path() { printf '%s/.harness/config' "$TARGET"; }
manifest_path() { printf '%s/.harness/manifest' "$TARGET"; }

# Load .harness/config into HV_* variables. Never sources the file.
config_load() {
  local file line key val
  file=$(config_path)
  [ -f "$file" ] || return 1
  while IFS= read -r line || [ -n "$line" ]; do
    case $line in '' | '#'*) continue ;; esac
    key=${line%%=*}
    val=${line#*=}
    list_has "$ANSWER_KEYS" "$key" || continue
    printf -v "HV_$key" '%s' "$val"
    export "HV_$key"
  done <"$file"
  return 0
}

config_write() {
  local file key var
  file=$(config_path)
  mkdir -p "$(dirname "$file")"
  {
    printf '# Generated by harness %s. Re-run `harness update` after editing.\n' "$HARNESS_VERSION"
    printf '# Values are literal (no quoting); one KEY=value per line.\n'
    for key in $ANSWER_KEYS; do
      var="HV_$key"
      printf '%s=%s\n' "$key" "${!var:-}"
    done
  } >"$file"
}

manifest_get() { # path -> sha or empty
  local file
  file=$(manifest_path)
  [ -f "$file" ] || return 0
  awk -v p="$1" '{ sha = $1; $1 = ""; sub(/^ +/, ""); if ($0 == p) { print sha; exit } }' "$file"
}

# During a run, new manifest entries accumulate here and replace the old
# manifest at the end (manifest_commit).
manifest_record() { # path sha
  printf '%s  %s\n' "$2" "$1" >>"$HARNESS_TMP/manifest.new"
}

manifest_commit() {
  local new=$HARNESS_TMP/manifest.new
  touch "$new"
  sort -k2 "$new" >"$new.sorted"
  mkdir -p "$TARGET/.harness"
  cp "$new.sorted" "$(manifest_path)"
}

# Paths that were managed before this run but were not produced by it.
manifest_orphans() {
  local old new=$HARNESS_TMP/manifest.new
  old=$(manifest_path)
  [ -f "$old" ] || return 0
  touch "$new"
  awk 'NR == FNR { $1 = ""; sub(/^ +/, ""); seen[$0] = 1; next }
       { $1 = ""; sub(/^ +/, ""); if (!($0 in seen)) print }' "$new" "$old"
}
