#!/usr/bin/env bash
# PreToolUse(Bash): blocks destructive or guardrail-bypassing shell commands.
# Generated by harness (guard level: {{GUARD_LEVEL}}).
. "$(dirname "$0")/lib.sh"

LEVEL='{{GUARD_LEVEL}}'
DEFAULT_BRANCH='{{DEFAULT_BRANCH}}'
cmd=$(hook_field command)
[ -n "$cmd" ] || exit 0

has() { printf '%s' "$cmd" | grep -Eq -- "$1"; }

# Always blocked, at every level.
has 'rm[[:space:]]+(-[[:alnum:]-]+[[:space:]]+)*(/|/\*|~/?|\$HOME/?)([[:space:]]|;|&|\||$)' &&
  hook_block "recursive delete of a root or home directory"
{{#unless PROFILE_SOLO}}
has "git[[:space:]]+push[^;&|]*[[:space:]:+]$DEFAULT_BRANCH([[:space:]]|;|&|$)" &&
  hook_block "direct push to $DEFAULT_BRANCH; push a branch and open a PR"
{{/if}}
{{#if PROFILE_SOLO}}
: "$DEFAULT_BRANCH" # solo repo: pushing to the default branch is fine
{{/if}}

[ "$LEVEL" = relaxed ] && exit 0

# standard and strict
has 'git[[:space:]]+push([^;&|]*[[:space:]])(-f|--force)([[:space:]]|$)' &&
  hook_block "force-push rewrites shared history"
has '--no-verify' &&
  hook_block "--no-verify skips the checks that keep the repo healthy"
has '(curl|wget)[^|;&]*\|[[:space:]]*(sudo[[:space:]]+)?(ba|z|da)?sh([[:space:]]|$)' &&
  hook_block "piping a download straight into a shell"
has 'chmod[[:space:]]+(-R[[:space:]]+)?0?777' &&
  hook_block "world-writable permissions"
if has '(^|[[:space:]/])\.env(\.[[:alnum:]_.-]+)?([[:space:]]|;|&|\||$)' &&
  ! has '\.env\.(example|sample|template|dist)'; then
  hook_block "reading or writing .env files; use .env.example for the shape"
fi

[ "$LEVEL" = strict ] || exit 0

# strict only
has 'git[[:space:]]+push[^;&|]*--force-with-lease' &&
  hook_block "force-push (even with lease) is human-only in strict mode"
has 'git[[:space:]]+reset[[:space:]]+--hard' &&
  hook_block "git reset --hard discards work; ask a human"
has 'git[[:space:]]+(clean[[:space:]]+-[[:alnum:]]*f|checkout[[:space:]]+--[[:space:]]+\.)' &&
  hook_block "discarding uncommitted changes"
has 'gh[[:space:]]+pr[[:space:]]+merge|gh[[:space:]]+api[^|;&]*/merge' &&
  hook_block "merging is a human decision"

exit 0
